// Mock data for Studio app — brands, generations, moods, etc.

const BRANDS = [
  {
    id: "northwind",
    name: "Northwind Coffee",
    dot: "#7C5232",
    logoText: "NW",
    palette: ["#2A1F18", "#7C5232", "#E8DCC4", "#C9A86A", "#F5EFE3"],
    fontHeading: "Fraunces",
    fontBody: "Inter",
    voice: "Warm, unhurried, generous. We say 'cup' not 'beverage'. Avoid trendy slang. We're a third-place neighborhood roaster.",
    refs: 8,
    generations: 47,
    url: "northwindcoffee.com",
    created: "Jan 14, 2026",
  },
  {
    id: "lumen",
    name: "Lumen Studio",
    dot: "#5E5CE6",
    logoText: "LU",
    palette: ["#0F0F1A", "#5E5CE6", "#F4F4FB", "#E8E7FA"],
    fontHeading: "Inter",
    fontBody: "Inter",
    voice: "Confident and minimal. Architectural language. Short sentences.",
    refs: 12,
    generations: 24,
    url: "lumen.studio",
    created: "Feb 2, 2026",
  },
  {
    id: "atlas",
    name: "Atlas Outdoors",
    dot: "#1F7A5A",
    logoText: "AT",
    palette: ["#0E2A1F", "#1F7A5A", "#D7E5C7", "#E8D9B0", "#FBF7EE"],
    fontHeading: "Source Serif Pro",
    fontBody: "Inter",
    voice: "Earned authority. Specific, not aspirational. We say 'trail' not 'journey'.",
    refs: 5,
    generations: 12,
    url: "atlasoutdoors.co",
    created: "Mar 18, 2026",
  },
];

const MOODS = [
  { id: "none", name: "Just my brand", kind: "Default", group: "default", img: null },
  // Right now
  { id: "christmas", name: "Christmas", kind: "Seasonal", group: "now",
    img: (window.__resources && window.__resources["img1"]),
    until: "Dec 30", motifs: ["pine", "ornament", "warm light"], colors: ["#7A0E0E", "#0E5C2F", "#E8C66B"] },
  { id: "midsummer", name: "Midsummer", kind: "Seasonal", group: "now",
    img: (window.__resources && window.__resources["img2"]),
    until: "Aug 15", motifs: ["wildflower", "long light"], colors: ["#F4D35E", "#7BAE7F", "#E8DCC4"] },
  // Always
  { id: "minimalist-tech", name: "Minimalist Tech", kind: "Evergreen", group: "always",
    img: (window.__resources && window.__resources["img3"]),
    motifs: ["geometric", "negative space"], colors: ["#0E0E10", "#5E5CE6", "#F4F4FB"] },
  { id: "editorial", name: "Editorial", kind: "Evergreen", group: "always",
    img: (window.__resources && window.__resources["img4"]),
    motifs: ["serif", "high contrast"], colors: ["#101010", "#F0EAD6", "#A23B2D"] },
  { id: "sunset-warm", name: "Sunset Warm", kind: "Evergreen", group: "always",
    img: (window.__resources && window.__resources["img5"]),
    motifs: ["gradient", "soft grain"], colors: ["#F47B3F", "#D33F73", "#FBE5C2"] },
  { id: "bold-bauhaus", name: "Bold Bauhaus", kind: "Evergreen", group: "always",
    img: (window.__resources && window.__resources["img6"]),
    motifs: ["primary color", "geometric"], colors: ["#E63946", "#1D3557", "#F1FAEE"] },
  // Coming soon
  { id: "halloween", name: "Halloween", kind: "Seasonal", group: "soon",
    img: (window.__resources && window.__resources["img7"]),
    from: "Oct 1", motifs: ["pumpkin", "moonlight"], colors: ["#F2691B", "#1A0F1F", "#5E2D8C"] },
  { id: "lunar-newyear", name: "Lunar New Year", kind: "Seasonal", group: "soon",
    img: (window.__resources && window.__resources["img7"]),
    from: "Jan 20", motifs: ["paper lantern", "red gold"], colors: ["#C8102E", "#E8C547", "#1A0E0E"] },
];

// 4 sample images we reuse for "generated variants"
const STOCK = [
  (window.__resources && window.__resources["img9"]),
  (window.__resources && window.__resources["img10"]),
  (window.__resources && window.__resources["img11"]),
  (window.__resources && window.__resources["img12"]),
  (window.__resources && window.__resources["img13"]),
  (window.__resources && window.__resources["img14"]),
  (window.__resources && window.__resources["img15"]),
  (window.__resources && window.__resources["img16"]),
];

const HISTORY = [
  { id: "g_8jq2", brief: "Christmas sale, cozy living room with a glowing tree, 30% off",
    brand: "northwind", mood: "christmas", ar: "1:1", status: "complete", credits: 20, when: "3 hours ago",
    images: [STOCK[0], STOCK[3], STOCK[5], STOCK[2]] },
  { id: "g_7r4d", brief: "New espresso blend launch, hands holding a warm mug, soft window light",
    brand: "northwind", mood: "none", ar: "4:5", status: "complete", credits: 20, when: "Yesterday",
    images: [STOCK[1], STOCK[2], STOCK[0], STOCK[3]] },
  { id: "g_6h2k", brief: "Modern interface mockup floating, minimalist, deep violet field",
    brand: "lumen", mood: "minimalist-tech", ar: "16:9", status: "complete", credits: 20, when: "Yesterday",
    images: [STOCK[7], STOCK[2], STOCK[7], STOCK[2]] },
  { id: "g_5p9w", brief: "Trail running shoe in alpine grass at golden hour",
    brand: "atlas", mood: "sunset-warm", ar: "9:16", status: "complete", credits: 20, when: "2 days ago",
    images: [STOCK[4], STOCK[3], STOCK[4], STOCK[3]] },
  { id: "g_4m1z", brief: "Editorial cover for a coffee field journal, serif lockup",
    brand: "northwind", mood: "editorial", ar: "4:5", status: "partial", credits: 15, when: "2 days ago",
    images: [STOCK[5], STOCK[1], null, STOCK[5]] },
  { id: "g_3a0p", brief: "Studio launch announcement, geometric Bauhaus shapes",
    brand: "lumen", mood: "bold-bauhaus", ar: "1:1", status: "complete", credits: 20, when: "5 days ago",
    images: [STOCK[7], STOCK[2], STOCK[7], STOCK[2]] },
];

const PLANS = [
  { id: "free", name: "Free", price: 0, brands: 1, seats: 1, credits: 50, features: ["1 brand", "1 seat", "50 credits / month", "Standard model"] },
  { id: "starter", name: "Starter", price: 19, brands: 3, seats: 1, credits: 400, features: ["3 brands", "1 seat", "400 credits / month", "All Moods"] },
  { id: "pro", name: "Pro", price: 49, brands: 10, seats: 3, credits: 1000, features: ["10 brands", "3 seats", "1,000 credits / month", "Premium model"] , popular: true},
  { id: "business", name: "Business", price: 149, brands: 30, seats: 10, credits: 4000, features: ["30 brands", "10 seats", "4,000 credits / month", "Priority queue"] },
  { id: "agency", name: "Agency", price: 399, brands: 100, seats: 30, credits: 12000, features: ["100 brands", "30 seats", "12,000 credits / month", "API access", "White-label"] },
];

const TOPUPS = [
  { credits: 200, price: 9 },
  { credits: 750, price: 29, best: true },
  { credits: 2500, price: 79 },
];

const INVOICES = [
  { date: "Apr 15, 2026", amount: "$49.00", status: "paid", number: "INV-0142" },
  { date: "Mar 15, 2026", amount: "$49.00", status: "paid", number: "INV-0128" },
  { date: "Feb 15, 2026", amount: "$49.00", status: "paid", number: "INV-0114" },
  { date: "Jan 15, 2026", amount: "$49.00", status: "paid", number: "INV-0098" },
];

const PROJECTS = [
  {
    id: "p_holiday26",
    name: "Holiday 2026 campaign",
    brand: "northwind",
    cover: STOCK[0],
    accent: "#7A0E0E",
    status: "active",
    description: "Full holiday push — homepage hero, social ads, in-store cards, and the email lockup. Cozy, generous, never cute.",
    created: "Nov 02, 2026",
    updated: "2 hours ago",
    collaborators: ["SK","RM","AB"],
    stats: { generations: 14, assets: 9, credits: 280 },
    prompts: [
      { id: "pr_01", text: "Christmas sale, cozy living room with a glowing tree, 30% off",
        when: "2 hours ago", mood: "christmas", ar: "1:1", credits: 20, used: 4, total: 4,
        outputs: [STOCK[0], STOCK[3], STOCK[5], STOCK[2]],
        assetsUsed: ["ref_tree_01", "logo_NW", "font_fraunces"], status: "complete" },
      { id: "pr_02", text: "Hands holding a warm mug at golden hour, 30% off badge top-right",
        when: "Yesterday", mood: "christmas", ar: "4:5", credits: 20, used: 3, total: 4,
        outputs: [STOCK[1], STOCK[3], STOCK[2], null],
        assetsUsed: ["ref_mug_warm", "logo_NW", "palette_holiday"], status: "partial" },
      { id: "pr_03", text: "Editorial cover for the holiday field journal, serif lockup",
        when: "2 days ago", mood: "editorial", ar: "4:5", credits: 20, used: 4, total: 4,
        outputs: [STOCK[5], STOCK[1], STOCK[0], STOCK[5]],
        assetsUsed: ["ref_journal", "logo_NW_mono", "font_fraunces"], status: "complete" },
      { id: "pr_04", text: "Garland over wooden countertop, espresso machine softly in focus",
        when: "3 days ago", mood: "christmas", ar: "16:9", credits: 20, used: 4, total: 4,
        outputs: [STOCK[2], STOCK[0], STOCK[3], STOCK[1]],
        assetsUsed: ["ref_machine", "logo_NW"], status: "complete" },
    ],
    assetLibrary: [
      { id: "logo_NW", kind: "Logo", name: "Northwind primary", thumb: "logo", count: 12 },
      { id: "logo_NW_mono", kind: "Logo", name: "Northwind mono", thumb: "logo-mono", count: 4 },
      { id: "ref_tree_01", kind: "Reference", name: "Christmas tree, low light", thumb: STOCK[0], count: 6 },
      { id: "ref_mug_warm", kind: "Reference", name: "Warm mug, hands", thumb: STOCK[1], count: 5 },
      { id: "ref_journal", kind: "Reference", name: "Field journal cover", thumb: STOCK[5], count: 3 },
      { id: "ref_machine", kind: "Reference", name: "Espresso machine bokeh", thumb: STOCK[2], count: 2 },
      { id: "palette_holiday", kind: "Palette", name: "Holiday accent palette", thumb: "palette", count: 8 },
      { id: "font_fraunces", kind: "Font", name: "Fraunces — display", thumb: "font", count: 14 },
    ],
  },
  {
    id: "p_spring",
    name: "Spring blends launch",
    brand: "northwind",
    cover: STOCK[1],
    accent: "#7BAE7F",
    status: "active",
    description: "New seasonal coffee SKUs. Soft, daylight, optimistic — but still us.",
    created: "Mar 04, 2026",
    updated: "5 days ago",
    collaborators: ["SK","RM"],
    stats: { generations: 8, assets: 6, credits: 160 },
    prompts: [
      { id: "pr_s1", text: "Pour-over kettle on a sun-warmed wooden table with wildflowers in a vase",
        when: "5 days ago", mood: "midsummer", ar: "1:1", credits: 20, used: 4, total: 4,
        outputs: [STOCK[1], STOCK[2], STOCK[3], STOCK[0]],
        assetsUsed: ["ref_kettle", "logo_NW"], status: "complete" },
      { id: "pr_s2", text: "Bag of new spring blend, soft light, top-down with petals scattered",
        when: "1 week ago", mood: "midsummer", ar: "4:5", credits: 20, used: 4, total: 4,
        outputs: [STOCK[3], STOCK[1], STOCK[2], STOCK[0]],
        assetsUsed: ["ref_bag", "logo_NW", "font_fraunces"], status: "complete" },
    ],
    assetLibrary: [
      { id: "logo_NW", kind: "Logo", name: "Northwind primary", thumb: "logo", count: 8 },
      { id: "ref_kettle", kind: "Reference", name: "Pour-over kettle", thumb: STOCK[1], count: 4 },
      { id: "ref_bag", kind: "Reference", name: "Coffee bag mockup", thumb: STOCK[3], count: 4 },
      { id: "palette_spring", kind: "Palette", name: "Spring soft palette", thumb: "palette", count: 6 },
      { id: "font_fraunces", kind: "Font", name: "Fraunces — display", thumb: "font", count: 8 },
    ],
  },
  {
    id: "p_lumen_launch",
    name: "Lumen v2 launch",
    brand: "lumen",
    cover: STOCK[7],
    accent: "#5E5CE6",
    status: "active",
    description: "Architectural, minimal, confident. Deep violet field, geometry, restrained type.",
    created: "Feb 14, 2026",
    updated: "Yesterday",
    collaborators: ["RM","JT","AB","SK"],
    stats: { generations: 11, assets: 7, credits: 220 },
    prompts: [
      { id: "pr_l1", text: "Modern interface mockup floating, minimalist, deep violet field",
        when: "Yesterday", mood: "minimalist-tech", ar: "16:9", credits: 20, used: 4, total: 4,
        outputs: [STOCK[7], STOCK[2], STOCK[7], STOCK[2]],
        assetsUsed: ["logo_LU", "ref_ui_mock"], status: "complete" },
      { id: "pr_l2", text: "Studio launch announcement, geometric Bauhaus shapes",
        when: "5 days ago", mood: "bold-bauhaus", ar: "1:1", credits: 20, used: 4, total: 4,
        outputs: [STOCK[7], STOCK[2], STOCK[7], STOCK[2]],
        assetsUsed: ["logo_LU", "palette_lumen"], status: "complete" },
    ],
    assetLibrary: [
      { id: "logo_LU", kind: "Logo", name: "Lumen mark", thumb: "logo", count: 11 },
      { id: "ref_ui_mock", kind: "Reference", name: "UI mockup base", thumb: STOCK[7], count: 6 },
      { id: "palette_lumen", kind: "Palette", name: "Lumen accent", thumb: "palette", count: 11 },
    ],
  },
  {
    id: "p_atlas",
    name: "Trail collection",
    brand: "atlas",
    cover: STOCK[4],
    accent: "#C97A3F",
    status: "draft",
    description: "Sunset-warm shots of the new alpine trail line.",
    created: "Apr 10, 2026",
    updated: "1 week ago",
    collaborators: ["JT"],
    stats: { generations: 3, assets: 4, credits: 60 },
    prompts: [
      { id: "pr_a1", text: "Trail running shoe in alpine grass at golden hour",
        when: "1 week ago", mood: "sunset-warm", ar: "9:16", credits: 20, used: 4, total: 4,
        outputs: [STOCK[4], STOCK[3], STOCK[4], STOCK[3]],
        assetsUsed: ["ref_shoe", "logo_AT"], status: "complete" },
    ],
    assetLibrary: [
      { id: "logo_AT", kind: "Logo", name: "Atlas wordmark", thumb: "logo", count: 3 },
      { id: "ref_shoe", kind: "Reference", name: "Trail shoe, alpine", thumb: STOCK[4], count: 3 },
      { id: "palette_atlas", kind: "Palette", name: "Atlas earth tones", thumb: "palette", count: 4 },
      { id: "font_source_serif", kind: "Font", name: "Source Serif Pro", thumb: "font", count: 3 },
    ],
  },
];

Object.assign(window, { BRANDS, MOODS, STOCK, HISTORY, PLANS, TOPUPS, INVOICES, PROJECTS });
